# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
development:
  APP_HOST: http://127.0.0.1:3000

  OUATH_TWITTER_KEY: "xDNGY6kllSIZugSyNDeqSIouV"
  OUATH_TWITTER_SECRET: "P2YHWVtHNxjLJJbBwPH9BvGYCAmLzUvxDAzfvyCGSGIDWR1oCn"

  OUATH_FACEBOOK_KEY: "523861567762293"
  OUATH_FACEBOOK_SECRET: "5c717ec2ea8edf84c720558c8e559e07"

  OUATH_GITHUB_KEY: "b4082d01c8d4de9f79ae"
  OUATH_GITHUB_SECRET: "127655b58cf9b5d13faeb6e2d403fd12b821c34c"
  OAUTH_GITHUB_CALLBACK_URL: http://localhost:3000/home/oauth/callback?provider=github

# AWS
  S3_BUCKET: "flcards"
  S3_ACCESS_KEY_ID: "AKIAJ5WAJHUPTPKILPLQ"
  S3_SECRET_ACCESS_KEY: "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"

production:
  APP_HOST: http://127.0.0.1:3000
